/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as IncomeIndexRouteImport } from './routes/income/index'
import { Route as ExpenseIndexRouteImport } from './routes/expense/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as ReportIndexRouteImport } from './routes/report/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeIndexRoute = IncomeIndexRouteImport.update({
  id: '/income/',
  path: '/income/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseIndexRoute = ExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/': typeof CategoryIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expense/': typeof ExpenseIndexRoute
  '/income/': typeof IncomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expense': typeof ExpenseIndexRoute
  '/income': typeof IncomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/': typeof CategoryIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expense/': typeof ExpenseIndexRoute
  '/income/': typeof IncomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/category/'
  | '/dashboard/'
  | '/expense/'
  | '/income/'
  | '/login/'
  | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category' | '/dashboard' | '/expense' | '/income' | '/login' | '/report'
  id:
  | '__root__'
  | '/'
  | '/category/'
  | '/dashboard/'
  | '/expense/'
  | '/income/'
  | '/login/'
  | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExpenseIndexRoute: typeof ExpenseIndexRoute
  IncomeIndexRoute: typeof IncomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income/': {
      id: '/income/'
      path: '/income'
      fullPath: '/income/'
      preLoaderRoute: typeof IncomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/': {
      id: '/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof ExpenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExpenseIndexRoute: ExpenseIndexRoute,
  IncomeIndexRoute: IncomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReportIndexRoute: ReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
